### PR TITLE
Fixes the issue where the code isn't able to properly check the compl…

### LINKED ISSUE #799: The checkStage flag doesn't properly check past successful stages
Hello,

Under the file ReleaseNotesFunctions.ts, line 641 to 643, we check that both the "state" and "result" properties equals to specific values ("2" and "0" respectively). When testing the endpoint in question (https://dev.azure.com/{organizationName}/{projectName}/_apis/build/builds/{buildId}/Timeline), we found out that it doesn't return any integers, but the following values instead: 
- For state: "completed"
- For result: "succeeded"

So the detection of any past successful build for a specific stage has never worked for us because of this. I will try to do a pull request that will be covering the problem. 

Thank you.

### PR DESCRIPTION
**Pull request by ddprince-yaksa**
…eted state and the succeeded result for a specific stage. Fixes #799.

### What problem does this PR address?
Fixes #799 
  
### Is there a related Issue?
#799

### CODE REVIEW

**Comment by rfennell** [comment]
Thanks for the PR, other than a small fix to meet the strict TSLinting I have configured it look good to me. It is currently running through the release pipelines and its tests. However, as you point out this bit of code was obviously not properly being exercised.

**Comment by ddprince-yaksa** [comment]
Hi @rfennell, it has been a pleasure! I though it would be a great idea to participate and fix it for the whole community. Your Azure DevOps extension is really useful for us. Thanks a lot for it! Have a great day/night!

**Comment by rfennell** [comment]
Sorry it took a while to get published to the Marketplace, but it has just completed as 3.9.6. The delay was due to a problem with the Snky analysis service yesterday evening that has cleared this morning

**Comment by ddprince-yaksa** [comment]
No problem, thanks for keeping me posted! &#128578;

[cid:Yaksa_b93d2afc-299a-4976-8a48-5195b5b62235.png]<http://yaksa.ca/>
David Drouin-Prince
Web Consultant
(514) 382-9460 #713<tel:(514)%20382-9460>
800 rue du Square-Victoria Suite 620
Montreal, QC H4Z 1A1
[cid:yaksa_facebook_544c78fc-de6b-4928-bdc4-36c2428a4955.png]<https://www.facebook.com/YaksaWebSolutions/>  [cid:yaksa_linked_1b7221fd-44cd-44fa-ac1d-f9fbd3ddee30.png]  <https://www.linkedin.com/company/yaksa>

**Pull request merged**
