### PR TITLE
Fixing attribute Parent in templates

### PR DESCRIPTION
**Pull request by elReiUrraca**

### CODE REVIEW

**Comment by elReiUrraca** [comment]
not sure if this works for versions previous to V3. I'll close by now

**Comment by rfennell** [comment]
I had a quick look at your commit and you should not need the `System.Parent` string. The JSON that is being matched is the `relations` which is in the form

```
            "relations": [{
                    "rel": "System.LinkTypes.Hierarchy-Reverse",
                    "url": "https://dev.azure.com/blackmarble-source/9bc48086-6780-43c5-9019-b7ae5ad6ba00/_apis/wit/workItems/119853",
                    "attributes": {
                        "isLocked": false,
                        "name": "Parent"
                    }
                }
            ],
```

so just contains the word `Parent`

As to the comment about V2 & V3 

- There is only active development in V3
- V2 is still shipped to allow people to migrate (I will remove it from the package soon) 
- V2 never had support for this form of parents and children lookup

**Comment by elReiUrraca** [comment]
hi @rdeveen! Hope you are doing well.
Yesterday I've tried the plugin and the 'System' add was mandatory for the template to display the parent ID.
Are you sure this works as it is?

**Comment by elReiUrraca** [comment]
Also, I would like to apologise for not following the contribution guidelines. Will take care.

**Pull request closed without merging**
