### PR TITLE
Added a fail through check for the project ID

### PR DESCRIPTION
**Pull request by rfennell**
### What problem does this PR address?
After merging #pr937 it was found that the process of getting WI/CS details could fail due to a missing project ID.

Code has been added to try two locations for the projects ID
- The originally used property
- If this is null then it falls back to the extracting the value from the JSON  

Also in the process of debuging this add a bit more logging

### CODE REVIEW

**Comment by LouisSung** [comment]
Thank you for the detailed testing and quick check :D

I also review the change, doesn’t it look weird? Why using the `&&` here? :o
A583F4E3-01B6-43BA-B77E-7423FB0EB842

**Comment by rfennell** [comment]
It is a

` item to null check && if not null value || if null value`

Is there a shorter syntax?

I know enough Node to be dangerous :)

**Comment by LouisSung** [comment]
Oh you mean the ternary operator? `falsyableItem ? truthy : falsy`?
It’s different from `falsyableItem || fallbackItem`

**Comment by rfennell** [comment]
Oops I got it from Stackoverflow, and confused two forms. I will tidy that and rebuild

**Comment by LouisSung** [comment]
undefined && undefined || value === (undefined && undefined) || value === undefined || value
Since logic and has higher priority.
It still work but kind of duplicated
https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by rfennell** [comment]
Thanks for the guidance, I will make the before I release the update

**Comment by LouisSung** [comment]
I think the `xxx || yyy` is better than `xxx ? xxx : yyy` in this situation since the former one is used for fallback and therefore is more readable and correct for the semantic point of view :)


// actually the better choice for null check is Nullish Coalescing `??` introduced in typescript 3.7 (this extension is using 3.6 though)
// however, I think you should use `ll` here because you’d also want to fallback empty string

**Pull request merged**
