### PR TITLE
Use vsrm in dev.azure.com URI for release information

### PR DESCRIPTION
**Pull request by KapteinYvo**
### What problem does this PR address?
Issue 449
  
### Is there a related Issue?
449
  
### Have you...
not yet..

### CODE REVIEW

**Comment by rfennell** [comment]
On initial look it looks fine, just want to make sure it does not break anyone using the old API or on-prem TFS. Cannot see it will but I will check

**Comment by rfennell** [comment]
OK had more of a look, the strange thing is that there is meant to already be code in place do this fix. It should not be needed.

I have a branch where I am convert this task to use PowerShell 3 and the Azure DevOps API, I will incorporate your changes into the revised code and retest it on Azure DevOps and TFS 2018.

Just a question, what were you going to get the new API, had you changed something so it worked in the past?

**Comment by rfennell** [comment]
Found the problem in my code, the URL needed to be corrected in two places, I had only done it in one.

Your fix corrected this, thanks. I have merged it into my move to PS3. I will release it via that branches PR

Thanks for the assistance

**Comment by KapteinYvo** [comment]
Hi Richard,

Great I could be of any help in the issue. I was establishing a release
pipeline at a new client that has the requirement for release notes, so
this was a first attempt for me. I'll fetch the update when it comes
available, thanks!

Kind regards, Yvo

Op za 9 mrt. 2019 om 17:47 schreef Richard Fennell <notifications@github.com

**Pull request closed without merging**
