### PR TITLE
Adding Active Build/ReleaseID & Custom Handlebars Code "As a File"

### PR DESCRIPTION
**Pull request by htekdev**
### What problem does this PR address?
XplatGenerateReleaseNotes
There are two issues currently being faced by my organization:
1. We want to build release notes on-demand; Meaning, we need to have control of what build id to build from. With this change, we can now provide the "active" build id as an override. The parameter `overrideActiveBuildReleaseId` as a way to override the active build id, much like the parameter `overrideBuildReleaseId` overrides the compare build.
2. We are using custom handlebars helpers but we don't want to manage the handlebars package. The current workaround is to do some fancy logic on our end to get the content of the file and set it as the `customHandlebarsExtensionCode`. It made sense to include that logic in the task itself. The addition of the parameter `customHandlebarsExtensionCodeAsFile` was introduced to provide the `customHandlebarsExtensionCode` as a file which is different then `customHandlebarsExtensionFile`. I felt that it was more of a risk to change how `customHandlebarsExtensionFile` is used rather than just having a different way of populating `customHandlebarsExtensionCode`
  
### Have you...
- If you are willing, please enable me, as the Repo owner, to [edit your fork that contains your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so I can add any missing items such as the readme.md

### CODE REVIEW

**Comment by htekdev** [comment]
Can I get a review - @rfennell ?

**Comment by htekdev** [comment]
@rfennell? Any chance I can get a review? My organization is currently blocked due to the lack of this PR. Thanks in advance! :)

**Comment by rfennell** [comment]
I have been on holiday, only just got back. I will try to look at this PR this week.

Quick take, is I would have preferred to see two PRs, one for each features, but lets work with that we have

**Comment by rfennell** [comment]
All seems OK to me, given the issues caused by the way (for historic reasons and backward support) that extensions are loaded.

This is being releases as 3.86.9

Thanks for the contribution

**Pull request merged**
