### PR TITLE
Use wildcard regex as fall back when finding Json files

### PR DESCRIPTION
**Pull request by andyward**
I've implemented the same pattern as #490 and added some tests

### What problem does this PR address?

See #569 
  
Thanks!

### CODE REVIEW

**Comment by rfennell** [comment]
I'm happy with that code wise, and it is currently running through the validation pipeline.

My only comment is should the help text in the task.json say that regex is a supported option?

**Comment by andyward** [comment]
Sure. I'll add that. I'd overlooked the help.

**Comment by andyward** [comment]
Help's updated... Let me know if anything else needed.

**Comment by rfennell** [comment]
That's all fine and has just been published as 2.22.2. Thanks for the PR

**Pull request merged**
