### PR TITLE
Added relatedWorkItems as additional parent data for pipeline artifacts

### PR DESCRIPTION
**Pull request by keepcalmandbuild**
### What problem does this PR address?
GeneratereleaseNotes (XPlat version)
Added relatedWorkItems to pipeline artifacts if getAllParents is enabled. This is similar to the data available for the primary artifact.
  
### Is there a related Issue?
#1334 
  
### Have you...
- If you are willing, please enable me, as the Repo owner, to [edit your fork that contains your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so I can add any missing items such as the readme.md

### CODE REVIEW

**Comment by keepcalmandbuild** [comment]
@rfennell PR created, please be patient, I am not a developer and this is the first time I use github :)

**Comment by rfennell** [comment]
That all looks OK to me on a first look. I need to do some testing and a documentation updates for the new features, which I will do ASAP

Thanks for the contribution

**Comment by keepcalmandbuild** [comment]
Thank you very much, this is a great extension, I appreciate your work and your availability.

**Comment by rfennell** [comment]
You have added this functionality to the YAML multistage build, but I also think it makes sense to add it to Classic release. I have done this, and a documentation refresh, but cannot push my commit to your branch.

Can you confirm that you have [edited your fork that contains your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so I can add my commit

**Comment by keepcalmandbuild** [comment]
I see this:
image
I have also invited you to contribute to my fork.

**Comment by rfennell** [comment]
I have found some edge cases where the consumed artifact's parent work items were not being populated. I think I have tested all scenarios for

- Classic Build (not applicable)
- Classic Release
- MultiStage YAML

@keepcalmandbuild thanks for the contribution. It is being releases as 3.87.4

**Comment by keepcalmandbuild** [comment]
Thank you very much @rfennell !!!

**Pull request merged**
